## 6.다항 분류 모델의 성능평가
- sklearn.metrics.accuracy_score(y_true, y_pred) = (TP/TN) / (TP+TN+FP+FN)
- sklearn.metrics.precision_score(y_true, y_pred) = TP / (TP + FP)
- sklearn.metrics.recall_score(y_true, y_pred) = TP / (TP + FN)
- sklearn.metrics.f1_score(y_true, y_pred = 2 * (Precison * Recall) / (Precision + Recall)
- precision_score, recall_score, f1_score의 average parameter에 None, "micro", "macro", "weighted"를 사용해야함 (class가 binary가 아닌 경우 필수)
- 참고 : https://gaussian37.github.io/ml-concept-ml-evaluation/

In [26]:
from sklearn.metrics import confusion_matrix,precision_score,recall_score,accuracy_score,f1_score
import numpy as np

y_true = [0,1,0,0,1,2]
y_pred = [0,2,1,0,0,1]
print(confusion_matrix(y_true,y_pred))
print('accuracy : %.4f' % accuracy_score(y_true,y_pred))
print('-'*20)
# Precision : 예측이 True 인 것 중 실제도 True
# average=None, 각 class 별로 precision을 구해라

print(precision_score(y_true,y_pred,average=None))
print('precision(micro) : %.4f' % precision_score(y_true,y_pred,average = 'micro'))
print('precision(macro) : %.4f' % precision_score(y_true,y_pred,average = 'macro'))
print('precision(weighted) : %.4f' % precision_score(y_true,y_pred,average = 'weighted'))

[[2 1 0]
 [1 0 1]
 [0 1 0]]
accuracy : 0.3333
--------------------
[0.66666667 0.         0.        ]
precision(micro) : 0.3333
precision(macro) : 0.2222
precision(weighted) : 0.3333


In [27]:
from sklearn.metrics import classification_report
creport = classification_report(y_true,y_pred)
print(creport)
# average=None
# 예측을 0으로 한 것 중 실제 0인 것, 예측을 1로 한 것 중 실제 1, 예측을 2로 한 것 중 실제 2
a = [2/3,0/2,0/1]
print(a)

              precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.00      0.00      0.00         2
           2       0.00      0.00      0.00         1

    accuracy                           0.33         6
   macro avg       0.22      0.22      0.22         6
weighted avg       0.33      0.33      0.33         6

[0.6666666666666666, 0.0, 0.0]


In [28]:
# average = 'micro' -> accuracy
# 전체 중에서 맞춘 것
2/6

0.3333333333333333

In [29]:
# average = 'macro' -> average=None일때의 모든 값을 더해 class 개수로 나눈 것
sum(a)/3

0.2222222222222222

In [30]:
# precision 의 average='weighted'
# average=None일때의 모든 값에 각 class의 데이터 개수를 곱하여 합을 구하고
# 전체 데이터 개수로 나눈 것
import pandas as pd
a = [2/3,0/2,0/1]
b = [3,2,1]
a = pd.Series(a)
b = pd.Series(b)
(a*b).sum()/6

0.3333333333333333